sudo: false
language: cpp

addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
      - scons
      - g++-5
      - gcc-5
      - libgtest-dev
      - doxygen

compiler:
  - clang
  - gcc

before_script:
  - cd /home/travis
  - mkdir gtest
  - cd gtest
  - cmake /usr/src/gtest
  - cmake --build .
  - cd $TRAVIS_BUILD_DIR

script:
  - if [ "$CXX" = "clang++" ]; then scons --clang --travis; fi
  - if [ "$CXX" = "g++" ]; then scons --travis; fi

after_success: ./ghp_upload.sh
